"""
CI drift gate for the vendored COMMAND-UI bundle.

The unified UI source of truth is ``packages/vigil-ui/``. Each plane server (this offense
console + the SIGIL sovereign cockpit) serves a VENDORED, git-tracked copy of that bundle
from its ``static/`` dir, produced by ``packages/vigil-ui/sync.sh`` (no build tooling: it
copies the JS/HTML and concatenates ``tokens.css`` + ``components.css`` → ``style.css``).

Before this gate the committed static dirs had silently rotted to the pre-unification
per-plane SPAs (an edit to the source never reached the served bytes, so a plane server run
directly served a STALE UI). This test fails the moment the vendored bytes drift from source —
so every UI change stays "clearly wired" all the way to what is actually served, and the fix is
always the same one command: ``bash packages/vigil-ui/sync.sh``.
"""

from __future__ import annotations

from pathlib import Path

import pytest

# .../console/tests/test_ui_vendor_sync.py → repo root is 6 parents up
_REPO = Path(__file__).resolve().parents[6]
_SRC = _REPO / "packages" / "vigil-ui"
_TARGETS = [
    _REPO / "engine" / "crucible" / "framework" / "v2" / "console" / "static",
    _REPO / "apps" / "sigil" / "sigil" / "ui" / "static",
]
# Must match packages/vigil-ui/sync.sh (COPY + STYLE_PARTS).
_COPY = ("ui.js", "manual.js", "app.js", "index.html")
_STYLE_PARTS = ("tokens.css", "components.css")
_BUNDLE = _COPY + ("style.css",)


def _built_style_css() -> bytes:
    """Reproduce sync.sh's style.css: a fixed header line, then each part followed by a newline
    (``echo`` header; then per part ``cat`` + ``echo``)."""
    out = "/* GENERATED by packages/vigil-ui/sync.sh — do not edit here; edit packages/vigil-ui/{tokens,components}.css */\n"
    for part in _STYLE_PARTS:
        out += (_SRC / part).read_text(encoding="utf-8") + "\n"
    return out.encode("utf-8")


def _tid(target: Path) -> str:
    return target.parent.parent.name if target.name == "static" else target.name


@pytest.mark.parametrize("target", _TARGETS, ids=[_tid(t) for t in _TARGETS])
def test_vendored_bundle_is_byte_identical_to_source(target: Path) -> None:
    """Each plane's vendored bundle == the packages/vigil-ui/ source, byte for byte."""
    for f in _COPY:
        assert (target / f).read_bytes() == (_SRC / f).read_bytes(), (
            f"{target.relative_to(_REPO)}/{f} has drifted from packages/vigil-ui/{f} — "
            f"run `bash packages/vigil-ui/sync.sh`")
    assert (target / "style.css").read_bytes() == _built_style_css(), (
        f"{target.relative_to(_REPO)}/style.css has drifted from tokens.css+components.css — "
        f"run `bash packages/vigil-ui/sync.sh`")


@pytest.mark.parametrize("target", _TARGETS, ids=[_tid(t) for t in _TARGETS])
def test_vendored_dir_has_no_stale_extra_files(target: Path) -> None:
    """The vendored dir is EXACTLY the unified bundle — no leftover legacy files (e.g. the old
    graph.js / styles.css) that a stale SPA would reference."""
    present = {p.name for p in target.iterdir() if p.is_file()}
    extra = present - set(_BUNDLE)
    assert not extra, f"{target.relative_to(_REPO)} has stale non-bundle files: {sorted(extra)}"


def test_both_plane_bundles_are_byte_identical() -> None:
    """Both plane servers serve the SAME bytes (the auditability invariant sync.sh asserts)."""
    a, b = _TARGETS
    for f in _BUNDLE:
        assert (a / f).read_bytes() == (b / f).read_bytes(), (
            f"{f} differs between {a.relative_to(_REPO)} and {b.relative_to(_REPO)} — "
            f"run `bash packages/vigil-ui/sync.sh`")
