#!/usr/bin/env bash
# Regenerate infra/supply-chain/strix.lock — the HASH-PINNED live-scan closure of vendor/strix.
#
# WHY A DEDICATED SCRIPT. vendor/strix's heavy live-scan deps (openai-agents[litellm], litellm,
# openai, docker, textual, cvss, caido-sdk-client + their transitive tree) are NOT in the offense
# framework lock (engine/crucible/framework/v2/requirements.lock.txt). They ship their own upstream
# uv lock (vendor/strix/uv.lock). This script exports that lock to a pip `--require-hashes` file so
# envs/build_envs.sh can install strix's extras HASH-LOCKED instead of resolving them fresh from PyPI
# on every operator install (the largest unlocked surface in the product — see docs/SUPPLY-CHAIN.md).
#
# OFFLINE + DETERMINISTIC. It exports the COMMITTED uv.lock with `--frozen` (no network, no
# re-resolution). vendor/strix is a uv WORKSPACE member of this repo, and the workspace root has no
# top-level uv.lock, so `uv export --frozen` inside the tree looks for the wrong lockfile. We
# therefore copy strix's standalone project metadata (pyproject.toml + uv.lock + README.md) to a temp
# directory OUTSIDE the workspace and export there, which reads vendor/strix/uv.lock directly.
#
# Requires: uv, Python 3.13 (the minor the VIGIL locks target).
set -euo pipefail
cd "$(dirname "$0")/../.."   # repo root

STRIX_DIR="vendor/strix"
OUT="infra/supply-chain/strix.lock"

command -v uv >/dev/null 2>&1 || { echo "[FATAL] uv is required to regenerate the strix lock (see docs/SUPPLY-CHAIN.md)" >&2; exit 1; }
[ -f "$STRIX_DIR/uv.lock" ] || { echo "[FATAL] $STRIX_DIR/uv.lock is missing — nothing to export from" >&2; exit 1; }

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
cp "$STRIX_DIR/pyproject.toml" "$STRIX_DIR/uv.lock" "$STRIX_DIR/README.md" "$tmp/"

# --no-emit-project: strix-agent itself is installed EDITABLE from the tree (-e ./vendor/strix), not
#   from the index, so it has no wheel to hash and must not appear here.
# --no-dev: dev/test tooling (mypy, ruff, pyinstaller, pytest) is not a runtime live-scan dependency.
body="$(cd "$tmp" && uv export --frozen --no-emit-project --no-dev --format requirements-txt)"

{
  cat <<'HDR'
# VIGIL — vendor/strix live-scan extras, HASH-PINNED for a `pip --require-hashes` install.
#
# DO NOT EDIT BY HAND. Regenerate with:  bash infra/supply-chain/gen-strix-lock.sh
#
# WHY. vendor/strix (the offense agent body) declares heavy live-scan deps — openai-agents[litellm],
# litellm, openai, docker, textual, cvss, caido-sdk-client and their transitive closure — that are
# NOT in the offense framework lock (engine/crucible/framework/v2/requirements.lock.txt). Before this
# lock they resolved FRESH from PyPI on every operator install (envs/build_envs.sh), the largest
# unlocked surface in the product and co-loaded with the offense engine. envs/build_envs.sh installs
# this file under `pip --require-hashes` (which refuses the WHOLE file if a single line is unpinned or
# unhashed), then installs vendor/strix itself editable --no-deps over it. See docs/SUPPLY-CHAIN.md §2.
#
# PROVENANCE. Exported OFFLINE from the committed vendor/strix/uv.lock (strix's own upstream lock)
# with `uv export --frozen` — NOT a fresh index resolution. Reproducible under Python 3.13.
HDR
  # Strip uv's own 2-line autogenerated header; our header above replaces it.
  printf '%s\n' "$body" | grep -v '^# This file was autogenerated by uv' \
                        | grep -v '^#    uv export'
} > "$OUT"

pins="$(grep -cE '^[A-Za-z0-9._-]+==' "$OUT")"
echo ">>> wrote $OUT ($pins hash-pinned requirements)"
