#!/usr/bin/env bash
# =============================================================================
# vigil-ui/sync.sh — AUTHOR-TIME vendoring of the committed UI bundle into both
# plane servers' static dirs. NO build tooling, NO network: it concatenates the
# CSS (tokens + components → style.css per manifest.build) and copies the JS +
# index into each target from manifest.targets. The output is git-tracked and
# byte-identical in both trees, so either server runs standalone and the diff is
# auditable. Re-runnable. Run after editing any packages/vigil-ui/* source.
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")"                 # packages/vigil-ui
ROOT="$(cd ../.. && pwd)"            # repo root
SRC="$(pwd)"

# manifest-driven (kept in sync with manifest.json by hand; asserted below)
STYLE_PARTS=(tokens.css components.css)
COPY=(ui.js app.js index.html)
TARGETS=("apps/sigil/sigil/ui/static" "engine/crucible/framework/v2/console/static")

for f in "${STYLE_PARTS[@]}" "${COPY[@]}"; do
  [ -f "$SRC/$f" ] || { echo "missing source: $f" >&2; exit 1; }
done

# build the single concatenated stylesheet once
BUILT_CSS="$(mktemp)"
{
  echo "/* GENERATED by packages/vigil-ui/sync.sh — do not edit here; edit packages/vigil-ui/{tokens,components}.css */"
  for p in "${STYLE_PARTS[@]}"; do cat "$SRC/$p"; echo; done
} > "$BUILT_CSS"

for t in "${TARGETS[@]}"; do
  dest="$ROOT/$t"
  mkdir -p "$dest"
  cp "$BUILT_CSS" "$dest/style.css"
  for f in "${COPY[@]}"; do cp "$SRC/$f" "$dest/$f"; done
  echo "vendored → $t  (style.css + ${COPY[*]})"
done
rm -f "$BUILT_CSS"

# verify byte-identical across targets (auditability invariant)
a="$ROOT/${TARGETS[0]}"; b="$ROOT/${TARGETS[1]}"
for f in style.css "${COPY[@]}"; do
  cmp -s "$a/$f" "$b/$f" || { echo "NOT byte-identical: $f" >&2; exit 1; }
done
echo "ok — both target bundles byte-identical"
