"""
memory.postmortem — engagement-end retrospective.

Reads everything MLS recorded during an engagement and writes a
structured postmortem to targets/<slug>/postmortem.md, plus updates
archetype priors based on the engagement's outcomes.

Idempotent — running it twice produces the same content the second
time, modulo any new rows recorded between runs.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from ..common import paths
from . import priors
from .store import Store


@dataclass
class PostmortemSummary:
    slug: str
    engagement_id: int
    archetype: str
    findings_total: int
    findings_by_severity: dict[str, int]
    hypotheses_total: int
    hypotheses_by_status: dict[str, int]
    payloads_by_outcome: dict[str, int]
    dead_ends_total: int
    playbook_yields: list[tuple[str, int, int]]  # (playbook_id, total_yield, sample_size)


def _query_summary(store: Store, slug: str) -> PostmortemSummary:
    eid = store.engagement_id(slug)
    arch_row = store.fetchone(
        "SELECT archetype FROM engagements WHERE id=?", (eid,)
    )
    archetype = arch_row["archetype"] if arch_row else ""

    findings_rows = store.fetchall(
        "SELECT severity, COUNT(*) as c FROM findings WHERE engagement_id=? GROUP BY severity",
        (eid,),
    )
    findings_total = sum(r["c"] for r in findings_rows)
    findings_by_severity = {r["severity"]: int(r["c"]) for r in findings_rows}

    hyp_rows = store.fetchall(
        "SELECT status, COUNT(*) as c FROM hypotheses WHERE engagement_id=? GROUP BY status",
        (eid,),
    )
    hyp_total = sum(r["c"] for r in hyp_rows)
    hyp_by_status = {r["status"]: int(r["c"]) for r in hyp_rows}

    payload_rows = store.fetchall(
        "SELECT outcome, COUNT(*) as c FROM payloads WHERE engagement_id=? GROUP BY outcome",
        (eid,),
    )
    payloads_by_outcome = {r["outcome"]: int(r["c"]) for r in payload_rows}

    de_row = store.fetchone(
        "SELECT COUNT(*) as c FROM dead_ends WHERE engagement_id=?", (eid,)
    )
    dead_ends_total = int(de_row["c"]) if de_row else 0

    pb_rows = store.fetchall(
        "SELECT playbook_id, SUM(findings_yielded) AS total_yield, "
        "       COUNT(*) AS sample_size "
        "FROM playbook_outcomes WHERE engagement_id=? GROUP BY playbook_id",
        (eid,),
    )
    playbook_yields = [
        (r["playbook_id"], int(r["total_yield"] or 0), int(r["sample_size"] or 0))
        for r in pb_rows
    ]

    return PostmortemSummary(
        slug=slug, engagement_id=eid, archetype=archetype,
        findings_total=findings_total,
        findings_by_severity=findings_by_severity,
        hypotheses_total=hyp_total,
        hypotheses_by_status=hyp_by_status,
        payloads_by_outcome=payloads_by_outcome,
        dead_ends_total=dead_ends_total,
        playbook_yields=playbook_yields,
    )


def _update_priors_from_engagement(store: Store, slug: str) -> int:
    """Update archetype_priors using this engagement's hypotheses + payloads.
    Returns the number of priors updated.
    """
    eid = store.engagement_id(slug)
    archetype = store.fetchone(
        "SELECT archetype FROM engagements WHERE id=?", (eid,)
    )["archetype"] or ""
    if not archetype:
        return 0

    n = 0

    # confirmed hypotheses → bump_success per (archetype, bug_class, surface)
    rows = store.fetchall(
        "SELECT bug_class, surface, status FROM hypotheses WHERE engagement_id=?",
        (eid,),
    )
    for r in rows:
        bc = r["bug_class"] or ""
        if not bc:
            continue
        if r["status"] == "confirmed":
            priors.bump_success(store, archetype, bc, r["surface"] or "")
        elif r["status"] in ("refuted", "deferred"):
            priors.bump_attempt(store, archetype, bc, r["surface"] or "")
        n += 1

    # successful payloads → bump_success
    pl = store.fetchall(
        "SELECT bug_class, target_surface, outcome FROM payloads WHERE engagement_id=?",
        (eid,),
    )
    for r in pl:
        bc = r["bug_class"] or ""
        if not bc:
            continue
        if r["outcome"] == "success":
            priors.bump_success(store, archetype, bc, r["target_surface"] or "")
        else:
            priors.bump_attempt(store, archetype, bc, r["target_surface"] or "")
        n += 1
    return n


def _render_markdown(s: PostmortemSummary) -> str:
    lines: list[str] = []
    lines.append(f"# Postmortem — `{s.slug}`")
    lines.append("")
    lines.append(
        f"Generated by MLS at {datetime.now(timezone.utc).isoformat(timespec='seconds')}."
    )
    lines.append(f"Archetype: `{s.archetype or '?'}`")
    lines.append("")
    lines.append("## Findings")
    if s.findings_total:
        lines.append(f"Total: **{s.findings_total}**.")
        for sev in ("Critical", "High", "Medium", "Low", "Info"):
            n = s.findings_by_severity.get(sev, 0)
            if n:
                lines.append(f"- {sev}: {n}")
    else:
        lines.append("(none recorded)")
    lines.append("")

    lines.append("## Hypotheses")
    if s.hypotheses_total:
        lines.append(f"Total: **{s.hypotheses_total}**.")
        for status, c in sorted(s.hypotheses_by_status.items()):
            lines.append(f"- {status}: {c}")
    else:
        lines.append("(none recorded)")
    lines.append("")

    lines.append("## Payloads")
    if s.payloads_by_outcome:
        for k, v in sorted(s.payloads_by_outcome.items()):
            lines.append(f"- {k}: {v}")
    else:
        lines.append("(none recorded)")
    lines.append("")

    lines.append("## Dead ends")
    lines.append(f"Recorded: **{s.dead_ends_total}**.")
    lines.append("")

    lines.append("## Playbook yield")
    if s.playbook_yields:
        for pb, y, n in s.playbook_yields:
            rate = y / n if n else 0.0
            lines.append(f"- `{pb}`: {y} findings across {n} sections (rate={rate:.2f})")
    else:
        lines.append("(no playbook outcomes recorded)")
    lines.append("")

    lines.append("## Priors updated")
    lines.append(
        "Archetype priors were updated based on hypothesis closures and payload "
        "outcomes recorded during this engagement.  See "
        "`framework/v2/.memory/store.sqlite` for the current state, or run "
        "`python3 -m framework.v2 memory priors --archetype "
        f"\"{s.archetype}\"`."
    )
    lines.append("")
    return "\n".join(lines)


def run(store: Store, slug: str) -> Path:
    """Generate the postmortem and update priors. Returns the path written."""
    summary = _query_summary(store, slug)
    _update_priors_from_engagement(store, slug)

    out = paths.target_dir(slug) / "postmortem.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_render_markdown(summary), encoding="utf-8")
    return out
