"""
reporter_agent — synthesises confirmed Findings into the technical report.

Reads `findings` with `critique_status='confirmed'` and writes (or
updates) `targets/<slug>/reports/technical.md`. The reporter is
deliberately conservative: it does NOT promote findings whose
critique-agent flagged objections, and it never modifies the
executive or remediation reports — those are human-written from the
technical one in this session.

A single step regenerates the technical report from scratch, so the
output is always consistent with the current blackboard state. It
runs only when the set of confirmed findings has changed since last
emission.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from ..common import paths
from typing import Iterator

from .base import Agent
from .blackboard import Blackboard, BlackboardEventRow
from .models import FindingPayload


class ReporterAgent(Agent):
    name = "reporter"

    def __init__(self, bb: Blackboard, engagement_slug: str) -> None:
        super().__init__(bb, engagement_slug)
        self._last_emitted_count = 0

    def should_run(self) -> bool:
        n = self._count_confirmed_findings()
        return n > self._last_emitted_count

    def step(self) -> int:
        confirmed = list(self._confirmed_findings())
        if not confirmed:
            return 0
        body = self._render(confirmed)
        out = paths.target_dir(self.slug) / "reports" / "technical.md"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(body, encoding="utf-8")
        self._last_emitted_count = len(confirmed)
        self._advance_cursor()
        return 1

    # ---- helpers ----

    def _confirmed_findings(self) -> Iterator[BlackboardEventRow]:
        rows = self.bb.read(
            engagement=self.engagement_id, kinds=["finding"],
        )
        for r in rows:
            if r.payload.get("critique_status") == "confirmed":
                yield r

    def _count_confirmed_findings(self) -> int:
        return sum(1 for _ in self._confirmed_findings())

    def _render(self, confirmed_events: list[BlackboardEventRow]) -> str:
        sev_order = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3, "Info": 4}
        findings: list[tuple[int, FindingPayload, int]] = []
        for ev in confirmed_events:
            try:
                f = FindingPayload.model_validate(ev.payload)
                findings.append((sev_order.get(f.severity, 5), f, ev.id))
            except Exception:
                continue
        findings.sort(key=lambda x: (x[0], x[1].finding_slug))

        ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
        lines: list[str] = [
            f"# Technical report — `{self.slug}`",
            "",
            f"Generated by reporter-agent at {ts} from blackboard state.",
            f"Confirmed findings: **{len(findings)}**.",
            "",
            "Each finding below has been:",
            "- Recorded as a Hypothesis,",
            "- Tested by an Action with a Result,",
            "- Reviewed by the critique-agent and signed off (`critique_status=confirmed`).",
            "",
            "## Index",
            "",
        ]
        for _sev, f, _eid in findings:
            lines.append(f"- [{f.finding_slug} — {f.title}](#{f.finding_slug.lower()})  `{f.severity}`")
        lines.append("")

        for _sev, f, eid in findings:
            lines += [
                f"## {f.finding_slug}",
                "",
                f"**Title:** {f.title}",
                f"**Severity:** {f.severity}",
                f"**Bug class:** `{f.bug_class}`",
                f"**Surface:** `{f.surface}`",
                f"**Derived from hypothesis:** `{f.derived_from_hypothesis or '(none)'}`",
                f"**Blackboard event id:** {eid}",
                "",
                "### Summary",
                "",
                f.summary,
                "",
                "### Impact",
                "",
                f.impact or "_(unspecified)_",
                "",
            ]
            if f.cvss_vector:
                lines += [f"**CVSS 3.1 vector:** `{f.cvss_vector}`  ", ""]
            if f.cvss_base is not None:
                lines += [f"**CVSS base score:** {f.cvss_base}", ""]
            lines += ["---", ""]

        lines += [
            "## Notes",
            "",
            "This file is regenerated by the reporter-agent on every "
            "engagement tick that changes the confirmed-findings set. "
            "Hand-edits will be overwritten.  For the executive summary "
            "and remediation roadmap, copy this content into "
            "`reports/executive.md` and `reports/remediation-roadmap.md` "
            "and adapt the framing per `framework/templates/`.",
            "",
        ]
        return "\n".join(lines)
